#!/bin/bash --login
 
# Job will run in the current directory (where you ran qsub)
#$ -cwd
 
# Mount a NVIDIA a100 GPU
#$ -l a100
 
# Request 4 CPU core
#$ -pe smp.pe 4
 
# Name the project name
#$ -N dppum-utests
 
# Join output file to .o
#$ -j y

# Purge modules
module purge
 
# Python 3.9 for GPUS: (uses CUDA 11.3, Anaconda3, 2021.11) - works on v100 AND A100 GPUs
module load apps/binapps/pytorch/1.11.0-39-gpu-cu113

# Name of the environment
ENV_NAME="dppum-torch"

source activate $ENV_NAME

# Check if activation was successful
if [ $? -eq 0 ]; then
    echo "Successfully activated $ENV_NAME"
else
    echo "Failed to activate $ENV_NAME. Aborting."
    exit 1
fi


echo -e "\nRunning unit tests in the environment $ENV_NAME:\n"
python3 -m pytest 
echo -e "\nFinished running unit test. The line above should hopefully say something like\n"
echo -e "=====xx passed, yy warnings"
echo -e "\nHopefully it will not have said any tests failed."
echo -e "\nFinished unit tests jobscript."
