#!/bin/bash --login
 
# Job will run in the current directory (where you ran qsub)
#$ -cwd
 
# Mount a NVIDIA a100 GPU
#$ -l a100
 
# Request 4 CPU core
#$ -pe smp.pe 4
 
# Name the project name
#$ -N ex1-train
 
# Join output file to .o
#$ -j y

# Purge modules
module purge
 
# Python 3.9 for GPUS: (uses CUDA 11.3, Anaconda3, 2021.11) - works on v100 AND A100 GPUs
module load apps/binapps/pytorch/1.11.0-39-gpu-cu113

# Name of the environment
ENV_NAME="dppum-torch"

source activate $ENV_NAME

# Check if activation was successful
if [ $? -eq 0 ]; then
    echo "Successfully activated $ENV_NAME"
else
    echo "Failed to activate $ENV_NAME. Aborting."
    exit 1
fi


echo -e "\nRunning a test of the environment $ENV_NAME:\n"
python3 -c "
from dppum.train import get_device_type
print(get_device_type())
"
echo -e "\nFinished running environment test. It should have said something like 'cuda:0'"

echo "Running experiments/train.py with settings for ex1."
# Run with -u flag so print statements should print immediately
python3 -u -m experiments.train -settings settings/settings_ex1_train.json

echo -e "\nFinished ex1 training jobscript."
